# Use postgres/example user/password credentials

services:
  waffle-db:
    container_name: waffle-db
    image: postgres
    restart: always
    volumes:
      - waffle-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: waffle
      POSTGRES_DB: waffle
    ports:
      - "5432:5432"

#  waffle-api:
#    container_name: waffle-api
#    build:
#      context: .
#    environment:
#      WAFFLE_USER: waffle
#      WAFFLE_PASSWORD: password
#      WAFFLE_DB_URL: jdbc:postgresql://waffle-db:5432/waffle

volumes:
  waffle-data: