# Use postgres/example user/password credentials

services:
  waffle-db:
    container_name: waffle-db-it
    image: postgres
    restart: always
    volumes:
      - waffle-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: waffle
      POSTGRES_DB: waffle
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "waffle", "-U", "waffle" ]
      interval: 1s
      timeout: 1s
      retries: 10

  waffle-api:
    container_name: waffle-api-it
    build:
      context: ../
    environment:
      WAFFLE_USER: waffle
      WAFFLE_PASSWORD: password
      WAFFLE_DB_URL: jdbc:postgresql://waffle-db:5432/waffle
    depends_on:
      waffle-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/price" ]
      interval: 5s
      timeout: 2s
      retries: 500

  waffle-it:
    container_name: waffle-it
    build:
      context: ../
      dockerfile: it/dockerfile
    depends_on:
      waffle-api:
        condition: service_healthy

volumes:
  waffle-data: